version: '3'

services:
  product-service:
    build: ./product-service
    ports:
      - "5001:5000"
    networks:
      - my-network
  cart-service:
    build: ./cart-service
    ports:
      - "5002:5000"
    networks:
      - my-network
  order-service:
    build: ./order-service
    ports:
      - "5003:5000"
    networks:
      - my-network
  checkout-service:
    build: ./checkout-service
    ports:
      - "5004:5000"
    networks:
      - my-network

networks:
  my-network: